apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: maxmartapp/api
      context: api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: maxmartapp/web
      context: web
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.jsx"
            dest: .
